[tool.ruff]
line-length = 119
extend-exclude = ["openmmforcefields/_version.py", "versioneer.py", "amber/", "charmm/"]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "UP",
]

[tool.ruff.lint.per-file-ignores]
"openmmforcefields/generators/__init__.py" = ["F401"]
"openmmforcefields/__init__.py" = ["F401"]
